# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('travelto', models.DateField()),
                ('travelfrom', models.DateField()),
            ],
            managers=[
                ('tripmanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=155)),
                ('username', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            managers=[
                ('usermanager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='exam.User'),
        ),
        migrations.AddField(
            model_name='trip',
            name='travellers',
            field=models.ManyToManyField(related_name='travellers', to='exam.User'),
        ),
    ]
