# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20160729_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='status',
            field=models.TextField(default='pending', max_length=250),
        ),
    ]
